### ISSUE TITLE
can we use this project?

### ISSUE THREAD

**Issue by tesch1** [mclarsen/svg_font_renderer#1]
Hi,
We'd like to use this project in SpinDrops(.org), but there's no license on it - how do you feel about licensing?
Cheers,
Michael

**Comment by mclarsen** [comment]
Not a problem. I just added one in #2. My original intent was parallelize the underlying nanosvg library to work on the GPU and do fast font rendering, but I never had the time.

**Comment by tesch1** [comment]
Awesome, thanks!
